// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class ClienteProdutoFavorito
    {
        [Key]
        public Guid ClienteId { get; set; }
        [Key]
        public Guid ProdutoId { get; set; }

        [ForeignKey(nameof(ClienteId))]
        [InverseProperty("ClienteProdutoFavorito")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey(nameof(ProdutoId))]
        [InverseProperty("ClienteProdutoFavorito")]
        public virtual Produto Produto { get; set; }
    }
}