// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class Cliente : Usuario
    {
        public Cliente()
        {
            ClienteProdutoFavorito = new HashSet<ClienteProdutoFavorito>();
            Pedido = new HashSet<Pedido>();
        }

        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();
        [Required(ErrorMessage = "Informe o nome")]
        [StringLength(150)]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Informe o sobrenome")]
        [StringLength(150)]
        public string Sobrenome { get; set; }
        [Required(ErrorMessage ="Informe o CPF")]
        [StringLength(11)]
        public string Cpf { get; set; }
        [Required(ErrorMessage = "Informe o e-mail")]
        [StringLength(100)]
        public new string Email { get; set; }
        [Required(ErrorMessage = "Informe a senha")]
        [StringLength(20)]
        public new string Senha { get; set; }
        [StringLength(11)]
        public string Celular { get; set; }
        public bool Ativo { get; set; } = true;
        [Column(TypeName = "date")]        
        public DateTime DataNascimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; } = DateTime.Now;

        [InverseProperty("Cliente")]
        public virtual ICollection<ClienteProdutoFavorito> ClienteProdutoFavorito { get; set; }
        [InverseProperty("Cliente")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}