// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class ClienteProdutoFavorito
    {
        public Guid ClienteId { get; set; }
        public Guid ProdutoId { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual Produto Produto { get; set; }
    }
}