// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class ClienteEndereco
    {
        public int Id { get; set; }
        public Guid ClienteId { get; set; }
        public string Logradouro { get; set; }
        public int? Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public string Cep { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCriacao { get; set; }

        public virtual Cliente Cliente { get; set; }
    }
}