// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class Cliente : Usuario
    {
        public Cliente()
        {
            ClienteEndereco = new HashSet<ClienteEndereco>();
            ClienteProdutoFavorito = new HashSet<ClienteProdutoFavorito>();
            Pedido = new HashSet<Pedido>();
        }

        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string Cpf { get; set; }        
        public string Celular { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataNascimento { get; set; }
        public DateTime DataCriacao { get; set; } = DateTime.Now;

        public virtual ICollection<ClienteEndereco> ClienteEndereco { get; set; }
        public virtual ICollection<ClienteProdutoFavorito> ClienteProdutoFavorito { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}