// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class Cupom
    {
        public Cupom()
        {
            Pedido = new HashSet<Pedido>();
        }

        public int Id { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFim { get; set; }
        public int Desconto { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}