// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class Marca
    {
        public Marca()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        public short Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Nome { get; set; }
        [Required]
        public bool Ativo { get; set; } = true;
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [InverseProperty("Marca")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}