// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class Modelagem
    {
        public Modelagem()
        {
            Produto = new HashSet<Produto>();
        }

        public short Id { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCriacao { get; set; }

        public virtual ICollection<Produto> Produto { get; set; }
    }
}