// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class PedidoItem
    {
        public Guid PedidoId { get; set; }
        public Guid ProdutoId { get; set; }
        public decimal ValorUnitario { get; set; }
        public decimal ValorUnitarioPago { get; set; }
        public int Quantidade { get; set; }

        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}