// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class Pedido
    {
        public Pedido()
        {
            PedidoItem = new HashSet<PedidoItem>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid ClienteId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        public int? CupomId { get; set; }
        public short StatusId { get; set; }

        [ForeignKey(nameof(ClienteId))]
        [InverseProperty("Pedido")]
        public virtual Cliente Cliente { get; set; }
        [ForeignKey(nameof(CupomId))]
        [InverseProperty("Pedido")]
        public virtual Cupom Cupom { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(StatusPedido.Pedido))]
        public virtual StatusPedido Status { get; set; }
        [InverseProperty("Pedido")]
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}