// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class PedidoItem
    {
        [Key]
        public Guid PedidoId { get; set; }
        [Key]
        public Guid ProdutoId { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal ValorUnitario { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal ValorUnitarioPago { get; set; }
        public int Quantidade { get; set; }

        [ForeignKey(nameof(PedidoId))]
        [InverseProperty("PedidoItem")]
        public virtual Pedido Pedido { get; set; }
        [ForeignKey(nameof(ProdutoId))]
        [InverseProperty("PedidoItem")]
        public virtual Produto Produto { get; set; }
    }
}