// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class Pedido
    {
        public Pedido()
        {
            PedidoItem = new HashSet<PedidoItem>();
        }

        public Guid Id { get; set; }
        public Guid ClienteId { get; set; }
        public DateTime DataCriacao { get; set; }
        public int? CupomId { get; set; }
        public short StatusId { get; set; }

        public virtual Cliente Cliente { get; set; }
        public virtual Cupom Cupom { get; set; }
        public virtual StatusPedido Status { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}