// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace API.Models
{
    public partial class Produto
    {
        public Produto()
        {
            ClienteProdutoFavorito = new HashSet<ClienteProdutoFavorito>();
            PedidoItem = new HashSet<PedidoItem>();
            ProdutoImagem = new HashSet<ProdutoImagem>();
        }

        public Guid Id { get; set; } = Guid.NewGuid();
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Slug { get; set; }
        public string ImagemPrincipal { get; set; }
        public short? MarcaId { get; set; }
        public short? CategoriaId { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal ValorVenda { get; set; }
        public decimal? ValorPromocional { get; set; }
        public int Estoque { get; set; }
        public bool Ativo { get; set; }
        public DateTime DataCriacao { get; set; } = DateTime.Now;
        public short CondicaoId { get; set; }
        public string Cor { get; set; }
        public short? MangaId { get; set; }
        public string Medidas { get; set; }
        public short? ModelagemId { get; set; }
        public string Observacoes { get; set; }
        public short TamanhoId { get; set; }
        public short? TecidoId { get; set; }

        public virtual Categoria Categoria { get; set; }
        public virtual Condicao Condicao { get; set; }
        public virtual Manga Manga { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelagem Modelagem { get; set; }
        public virtual Tamanho Tamanho { get; set; }
        public virtual Tecido Tecido { get; set; }
        public virtual ICollection<ClienteProdutoFavorito> ClienteProdutoFavorito { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
        public virtual ICollection<ProdutoImagem> ProdutoImagem { get; set; }
    }
}