// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    public partial class ProdutoImagem
    {
        [Key]
        [StringLength(50)]
        public string Imagem { get; set; }
        public Guid ProdutoId { get; set; }

        [ForeignKey(nameof(ProdutoId))]
        [InverseProperty("ProdutoImagem")]
        public virtual Produto Produto { get; set; }
    }
}