// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    [Index(nameof(CategoriaId), Name = "IX_Produto_CategoriaId")]
    [Index(nameof(CondicaoId), Name = "IX_Produto_CondicaoId")]
    [Index(nameof(MangaId), Name = "IX_Produto_MangaId")]
    [Index(nameof(MarcaId), Name = "IX_Produto_MarcaId")]
    [Index(nameof(ModelagemId), Name = "IX_Produto_ModelagemId")]
    [Index(nameof(TamanhoId), Name = "IX_Produto_TamanhoId")]
    [Index(nameof(TecidoId), Name = "IX_Produto_TecidoId")]
    public partial class Produto
    {
        public Produto()
        {
            ClienteProdutoFavorito = new HashSet<ClienteProdutoFavorito>();
            PedidoItem = new HashSet<PedidoItem>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Nome { get; set; }
        [StringLength(500)]
        public string Descricao { get; set; }
        public short? MarcaId { get; set; }
        public short? CategoriaId { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal ValorCompra { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal ValorVenda { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal? ValorPromocional { get; set; }
        public int Estoque { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }
        public short CondicaoId { get; set; }
        [Required]
        [StringLength(20)]
        public string Cor { get; set; }
        public short? MangaId { get; set; }
        [Required]
        [StringLength(200)]
        public string Medidas { get; set; }
        public short? ModelagemId { get; set; }
        [StringLength(300)]
        public string Observacoes { get; set; }
        public short TamanhoId { get; set; }
        public short? TecidoId { get; set; }

        [ForeignKey(nameof(CategoriaId))]
        [InverseProperty("Produto")]
        public virtual Categoria Categoria { get; set; }
        [ForeignKey(nameof(CondicaoId))]
        [InverseProperty("Produto")]
        public virtual Condicao Condicao { get; set; }
        [ForeignKey(nameof(MangaId))]
        [InverseProperty("Produto")]
        public virtual Manga Manga { get; set; }
        [ForeignKey(nameof(MarcaId))]
        [InverseProperty("Produto")]
        public virtual Marca Marca { get; set; }
        [ForeignKey(nameof(ModelagemId))]
        [InverseProperty("Produto")]
        public virtual Modelagem Modelagem { get; set; }
        [ForeignKey(nameof(TamanhoId))]
        [InverseProperty("Produto")]
        public virtual Tamanho Tamanho { get; set; }
        [ForeignKey(nameof(TecidoId))]
        [InverseProperty("Produto")]
        public virtual Tecido Tecido { get; set; }
        [InverseProperty("Produto")]
        public virtual ICollection<ClienteProdutoFavorito> ClienteProdutoFavorito { get; set; }
        [InverseProperty("Produto")]
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}