// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace API.Models
{
    [Index(nameof(Descricao), Name = "UQ__Tamanho__008BA9EF2E2004D4", IsUnique = true)]
    public partial class Tamanho
    {
        public Tamanho()
        {
            Produto = new HashSet<Produto>();
        }

        [Key]
        public short Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataCriacao { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataAtualizacao { get; set; }

        [InverseProperty("Tamanho")]
        public virtual ICollection<Produto> Produto { get; set; }
    }
}